version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - db
  db:
    image: postgres:13
    env_file: .env
    container_name: postgres_ieb
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports: 
      - 5432:5432

  redis:
    image: redis:7

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    command: bash -c "celery -A products beat & celery -A products worker --loglevel=debug"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: